language: python
sudo: required

python:
  - '3.6'
  - '3.6-dev'
  - '3.7-dev'
  - 'nightly'
  - 'pypy'

matrix:
  allow_failures:
    - python: '3.6-dev'
    - python: '3.7-dev'
    - python: 'nightly'
    - python: 'pypy'

install:
  - bash .travis/install.sh
  - pip install -U -r requirements-dev.txt

script:
  - .travis/run.sh 'PYTHONPATH=. python -m camisole languages'
  - .travis/run.sh 'PYTHONPATH=. python -m camisole test -vv'
  - .travis/run.sh 'python setup.py test'
