#!/bin/sh

set -e

pushpkg() {
    # $1 is the name of the package
    # $2-* are all the files to copy

    pkgname="$1"
    shift

    pushd $pkgname
    if [[ ! -d $pkgname ]]; then
        git clone ssh://aur@aur.archlinux.org/$pkgname.git
        pushd $pkgname
    else
        pushd $pkgname
        git pull --rebase
    fi

    for f in $*; do
        cp "../$f" .
    done

    git add .

    if ! git diff --quiet --exit-code --staged; then
        git commit -e -m '# Use :cq in vim to abort committing'

        read -p "git push now? (y/n) " -n 1 -r
        echo
        [[ ! $REPLY =~ ^[Yy]$ ]] && exit 1

        git push origin master
    fi

    popd
    popd
}

pushpkg camisole-git PKGBUILD .SRCINFO camisole-git.install camisole.service \
                     sysusers.conf _camisole

pushpkg camisole-languages PKGBUILD .SRCINFO
