#!/bin/sh

set -e

[[ ! -d camisole-git ]] && git clone ssh://aur@aur.archlinux.org/camisole-git.git
cd camisole-git

git pull

for f in PKGBUILD .SRCINFO camisole-git.install camisole.service sysusers.conf
do
	cp "../$f" .
done

git add .
git commit -e -m '# Use :cq in vim to abort committing'

read -p "git push now? (y/n) " -n 1 -r
echo
[[ ! $REPLY =~ ^[Yy]$ ]] && exit 1

git push
