# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base
  config.vm.box = "prologin/archlinux"

  # Networking
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  # tutturu -> 192.168.122.78
  config.vm.network "private_network", ip: "192.168.122.78"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    cd /tmp
    # install camisole-git from aur
    sudo -u vagrant pacaur -S --noconfirm camisole-git
    # enable & start camisole
    sudo systemctl enable camisole
    sudo systemctl start camisole
    # install camisole optdepends
    git clone https://aur.archlinux.org/camisole-git.git
    source camisole-git/PKGBUILD
    for f in "${optdepends[@]}"; do echo $f | cut -d: -f1; done | xargs sudo -u vagrant pacaur -S --noconfirm
  SHELL
end
